export const checkUSer = async(req,res, next) =>{
    try{

    }catch(error){
        next(error)
    }
}